### ISSUE TITLE
Drobne problemy

### ISSUE THREAD

**Issue by Klem7ens** [m32/ksef#1]
Cześć!
Świetna robota, moja znajomość pythona jest na bardzo podstawowym poziomie, ale dałem radę przetestować współpracę z bramką testową.
Drobne uwagi, pobieranie UPO sypie błędami że nie ma atrybutu .processing_code chyba powinien być użyty .status_code, przynajmniej po takiej podmianie pobrałem UPO z serwisu.
Traceback (most recent call last):
  File "c:\KSEF\Python\ksef-main\demo-upo.py", line 59, in <module>
    main()
  File "c:\KSEF\Python\ksef-main\demo-upo.py", line 54, in main
    cls.upo(sys.argv[1])
  File "c:\KSEF\Python\ksef-main\demo-upo.py", line 46, in upo
    if response.parsed.processing_code == 200:
AttributeError: 'ExceptionResponse' object has no attribute 'processing_code'

Na bramce testowej trafiła się faktura sprzedaży, w której nie było nazwy odbiorcy oraz adresu (był tylko NIP) - generuje to błąd i program się wysypuje. Nie wiem czy docelowo taka sytuacja jest w KSeF możliwa, ale dobrze byłoby obsłużyć ten wyjątek, niestety przerasta to moje możliwości. Poniżej błąd, który dostawałem:

Traceback (most recent call last):
  File "c:\KSEF\Python\ksef-main\demo-online.py", line 262, in <module>
    main()
  File "c:\KSEF\Python\ksef-main\demo-online.py", line 241, in main
    cls.query1(
  File "c:\KSEF\Python\ksef-main\demo-online.py", line 148, in query1
    response = api.zapytania.invoice.sync_detailed(
  File "c:\KSEF\Python\ksef-main\ksef\online\api\zapytania\invoice.py", line 130, in sync_detailed
    return _build_response(client=client, response=response)
  File "c:\KSEF\Python\ksef-main\ksef\online\api\zapytania\invoice.py", line 85, in _build_response
    parsed=_parse_response(client=client, response=response),
  File "c:\KSEF\Python\ksef-main\ksef\online\api\zapytania\invoice.py", line 57, in _parse_response
    response_200 = QueryInvoiceSyncResponse.from_dict(response.json())
  File "c:\KSEF\Python\ksef-main\ksef\online\models\query_invoice_sync_response.py", line 88, in from_dict
    invoice_header_list_item = InvoiceHeaderType.from_dict(invoice_header_list_item_data)
  File "c:\KSEF\Python\ksef-main\ksef\online\models\invoice_header_type.py", line 219, in from_dict
    subject_to = SubjectToType.from_dict(d.pop("subjectTo"))
  File "c:\KSEF\Python\ksef-main\ksef\online\models\subject_to_type.py", line 77, in from_dict
    issued_to_name = SubjectNameType.from_dict(_issued_to_name)
  File "c:\KSEF\Python\ksef-main\ksef\online\models\subject_name_type.py", line 53, in from_dict
    d = src_dict.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by m32** [comment]
Dzięki za testy.

Założenie jest tylko jedno - dokument musi być poprawny składniowo - przechodzi walidatora xsd - dodałem kilka plików do sprawdzenia poprawności dokumentu.

Wygeneruję sobie niepoprawnego xmla i zobaczę co daje ksef - w przyszłości podepnij dokument który odrzucił ksef - będzie mi łatwiej.

**Comment by m32** [comment]
nie daję rady wystawić błędnego pliku - jak nie mam nazwy nadawcy lub jego adresu to mi nie zapisuje takiego dokumentu

o dziwo jak ręcznie zmienię ilość i zapewne inne parametry z pozycji i nie będą one zgodne z nagłówkiem to taki dokument przyjmuje :)))))

**Comment by Klem7ens** [comment]
No właśnie nie byłem w stanie pobrać dokumentu, nie wpadłem na to żeby pobrać bezpośrednio z KSeFu :) Właśnie pobrałem i dołączyłem tutaj - nie wiem jak ktoś ten dokument wprowadził do platformy testowej, może tam nie ma wszystkich weryfikacji. 

[1894466533-20231006-98617E21BB28-7D.zip](https://github.com/m32/ksef/files/12848838/1894466533-20231006-98617E21BB28-7D.zip)

**Comment by m32** [comment]
dokument jest ok - validator xsd nie protestuje
w xmlu brak nazwy dla podmiotu2:
<Podmiot2>
    <DaneIdentyfikacyjne>
      <NIP>9999999999</NIP>
    </DaneIdentyfikacyjne>

po wysłaniu odszukuję jako moją fakturę, w respose content dostaję
"subjectBy":{"issuedByIdentifier":{"type":"onip","identifier":"8511172404"},"issuedByName":{"type":"fn","tradeName":null,"fullName":"Koziołek Matołek"}}
"subjectTo":{"issuedToIdentifier":{"type":"onip","identifier":"9999999999"},"issuedToName":null}

w strukturach KSeF-online.yaml za nazwę nadawcy odpowiada ten kawałek poniżej, rozumiem że pole issuedToName ma być obiektem z wymaganym polem type, które decyduje o dalszych polach w tym słowniku
null nigdzie nie występuje w tej strukturze - babol w generacji response w ksef czy wrapperze w pythonie ?
no i komu zadać te pytanie - w ksef ?
```
    SubjectNameType:
      type: object
      discriminator:
        mapping:
          fn: '#/components/schemas/SubjectFullNameType'
          none: '#/components/schemas/SubjectNoneType'
          pn: '#/components/schemas/SubjectPersonNameType'
        propertyName: type
      properties:
        tradeName:
          type: string
          maxLength: 256
          minLength: 1
        type:
          type: string
      required:
      - type
```

**Comment by m32** [comment]
chłopaki nie trzymają standardu :(, wstawiłem w kodzie wyjątek i teraz można się logować na test/demo/prod nawet jak klient nie ma przypisanej nazwy
